version: '3'
services:
  private:
    build: 
      dockerfile: ./docker/private.Dockerfile
      context: .
    volumes:
      - ./packages/private:/app/packages/private
    ports:
      - 8081:8081
    networks:
      - my_network
    
  public:
    build: 
      dockerfile: ./docker/public.Dockerfile
      context: .
    volumes:
      - ./packages/public:/app/packages/public
    ports:
      - 5173:5173
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: ai_jrnl
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network: